### ISSUE TITLE
Where to download the data set?

### ISSUE THREAD

**Issue by orihash** [M1thun/Dynamic-Hand-Gesture-Recognition-using-3D-CNN#2]
Can you please tell me where can I download the data set related to this repository Cha learn data set for gesture recognition ?

**Comment by M1thun** [comment]
https://gesture.chalearn.org/2016-looking-at-people-cvpr-challenge/isogd-and-congd-datasets

**Comment by darshu99** [comment]
> Can you please tell me where can I download the data set related to this repository Cha learn data set for gesture recognition ?

Sir did u get the dataset from that website ?
We have requested for the dataset. But still there is no response. Please help us sir
